version: '3'
services:
#  zookeeper:
#    image: wurstmeister/zookeeper
#    ports:
#      - "2181:2181"
#  kafka-service:
#    image: wurstmeister/kafka
#    ports:
#      - 9092:9092
#    environment:
#      #  refer https://hub.docker.com/r/landoop/fast-data-dev/	      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
#      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-service:9093,EXTERNAL://localhost:9092
#      KAFKA_LISTENERS: INTERNAL://kafka-service:9093,EXTERNAL://kafka-service:9092
#      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#    volumes:
#      - kafka:/var/run/docker.sock
#    depends_on:
#      - zookeeper

  redis:
    image: redis:6.0
    command: redis-server --requirepass default
    ports:
      - 6379:6379

  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_PASSWORD=Initial0
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4:4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@sap.com
      - PGADMIN_DEFAULT_PASSWORD=Initial0
    ports:
      - 8000:80
    links:
      - postgres:postgres

volumes:
  pgdata:
#  kafka:

